# Generated by Django 5.1.5 on 2025-01-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Введите название')),
                ('description', models.TextField(verbose_name='Введите описание рецепта')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите название ингридиента')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('unit', models.CharField(choices=[('грамм', 'грамм'), ('киллограмм', 'киллограмм'), ('миллилитров', 'миллилитров'), ('литров', 'литров'), ('штук', 'штук')], max_length=100, verbose_name='Выберите единицу измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.recipes', verbose_name='Выберите рецепт')),
            ],
        ),
    ]
