# Generated by Django 5.1.4 on 2025-01-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hastags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
    ]
