# Generated by Django 5.1.4 on 2025-01-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_adress', models.TextField(verbose_name='Введите ваш адресс')),
                ('pay', models.CharField(choices=[('Mbank', 'Mbank'), ('Optima', 'Optima'), ('Finca Bank ', 'Finca Bank'), ('При доставке', 'При доставке')], max_length=20)),
                ('card_number', models.PositiveIntegerField(verbose_name='Введите номер карты')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Введите номер телефона')),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
            ],
        ),
    ]
