# Generated by Django 5.1.4 on 2025-01-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_reviews'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='choice_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library.books', verbose_name='Выберите книгу'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(choices=[('Mbank', 'Mbank'), ('Optima', 'Optima'), ('Finca Bank ', 'Finca Bank'), ('При доставке', 'При доставке')], max_length=20, null=True, verbose_name='Выберите способ оплаты'),
        ),
    ]
